CXX := g++
CXXFLAGS := -std=c++11 -pthread
EXECUTABLE_SIMULATION = SimOhen
EXECUTABLE_SERVER = Server

SRC_FILES_SIMULATION = main.cpp my_socket.cpp
SRC_FILES_SERVER = Server/Server.c

OBJ_FILES_SIMULATION = $(SRC_FILES_SIMULATION:.cpp=.o)
OBJ_FILES_SERVER = $(SRC_FILES_SERVER:.cpp=.o)

all: $(EXECUTABLE_SIMULATION) $(EXECUTABLE_SERVER)

$(EXECUTABLE_SIMULATION): $(OBJ_FILES_SIMULATION)
    $(CXX) $(CXXFLAGS) -o $@ $^

$(EXECUTABLE_SERVER): $(OBJ_FILES_SERVER)
    $(CXX) $(CXXFLAGS) -o $@ $^

%.o: %.cpp
    $(CXX) $(CXXFLAGS) -c -o $@ $<

clean:
    rm -f $(OBJ_FILES_SIMULATION) $(OBJ_FILES_SERVER) $(EXECUTABLE_SIMULATION) $(EXECUTABLE_SERVER)
